name: Playwright Tests
on:
  push:
    branches:  main 
  pull_request:
    branches: main

jobs:
  build-rp:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: RP_PROD 
    env:
      PASSWORD_ADMIN: ${{secrets.PASSWORD_ADMIN}}
    steps:
      - uses: actions/checkout@v4
      - name: Check docker
        run: |
          docker --version
          docker compose version

      - name: Build RP
        run: docker compose -f docker/docker-compose.yml -p reportportal up -d --force-recreate

      - name: Check containers
        run: |
          docker compose -f docker/docker-compose.yml ps
          docker ps

      - name: Test application
        run: |
          curl -v http://localhost:8080/
          curl -v http://localhost:8080/ui/
      - name: D Logs
        run: |
          docker compose -f docker/docker-compose.yml logs -f

  run-tests:
    needs: build-rp
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: RP_PROD 
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      HEADLESS: ${{ vars.HEADLESS }}
      PASSWORD_ADMIN: ${{secrets.PASSWORD_ADMIN}}
      LOGIN_ADMIN: ${{secrets.LOGIN_ADMIN}}
      PASSWORD_DEFAULT: ${{secrets.PASSWORD_DEFAULT}}
      LOGIN_DEFAULT: ${{secrets.LOGIN_DEFAULT}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Chromium
      run: npx playwright install --with-deps chromium
    - name: Run Playwright smoke tests
      run: npm run test:smoke
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  
  teardown-rp:
    needs: run-tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Teardown RP
        run: docker compose -f docker/docker-compose.yml down --volumes --remove-orphans

      - name: check containers
        run: docker ps
 
